"""The `Message` type, mirroring Agno's `agno/models/message.py` trimmed to
the fields this project actually uses (no media, citations, references, or
checkpoint bookkeeping).

Pydantic `BaseModel` rather than a plain dataclass because messages cross the
API boundary (request bodies, SSE payloads, DB rows) and benefit from
validation/coercion there - unlike `ModelResponse`/`ToolExecution` in
`response.py`, which are internal-only plumbing between the model adapter and
the agent loop.

`tool_calls` is deliberately `Optional[List[Dict[str, Any]]]` - the raw,
provider-shaped dicts as returned by the model API, `arguments` still a JSON
string rather than a parsed object. Converting those into a typed
`FunctionCall` is a later stage's job; parsing them here would mean every
provider adapter has to agree on one shape before this module can exist.
"""

from __future__ import annotations

import json
import logging
from time import time
from typing import Any, Dict, List, Optional, Union
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field

from app.metrics import MessageMetrics

logger = logging.getLogger(__name__)


class Message(BaseModel):
    """A single message sent to, or received from, the model."""

    id: str = Field(default_factory=lambda: str(uuid4()))

    # One of system, user, assistant, or tool.
    role: str
    # The contents of the message.
    content: Optional[Union[List[Any], str]] = None

    # An optional name for the participant - differentiates participants that
    # share the same role.
    name: Optional[str] = None
    # Tool call that this message is responding to (role="tool" messages).
    tool_call_id: Optional[str] = None
    # Tool calls generated by the model. Raw provider dicts - arguments is
    # still a JSON string; parsing into FunctionCall happens elsewhere.
    tool_calls: Optional[List[Dict[str, Any]]] = None

    # --- Data not sent to the model API ---
    # The name of the tool that was called.
    tool_name: Optional[str] = None
    # Arguments passed to the tool.
    tool_args: Optional[Any] = None
    # Whether the tool call errored.
    tool_call_error: Optional[bool] = None
    # If True, the agent stops executing after this tool call.
    stop_after_tool_call: bool = False
    # Set when this message was fetched from history rather than produced
    # fresh in the current run.
    from_history: bool = False

    # Usage/timing for this message. Empty MessageMetrics by default;
    # populated on assistant messages once the model responds.
    metrics: MessageMetrics = Field(default_factory=MessageMetrics)

    # Unix timestamp the message was created.
    created_at: int = Field(default_factory=lambda: int(time()))

    model_config = ConfigDict(extra="allow", populate_by_name=True, arbitrary_types_allowed=True)

    def get_content_string(self) -> str:
        """Returns the content as a string, regardless of its underlying shape."""
        if isinstance(self.content, str):
            return self.content
        if isinstance(self.content, list):
            if len(self.content) == 0:
                return ""
            if isinstance(self.content[0], dict) and "text" in self.content[0]:
                return self.content[0].get("text", "")
            return json.dumps(self.content, ensure_ascii=False)
        return ""

    def to_dict(self) -> Dict[str, Any]:
        """Returns the message as a dictionary, dropping None/empty fields."""
        message_dict = {
            "id": self.id,
            "role": self.role,
            "content": self.content,
            "name": self.name,
            "tool_call_id": self.tool_call_id,
            "tool_calls": self.tool_calls,
            "tool_name": self.tool_name,
            "tool_args": self.tool_args,
            "tool_call_error": self.tool_call_error,
            "stop_after_tool_call": self.stop_after_tool_call,
            "from_history": self.from_history,
        }
        message_dict = {
            k: v
            for k, v in message_dict.items()
            if v is not None and not (isinstance(v, (list, dict)) and len(v) == 0)
        }

        if self.metrics:
            metrics_dict = self.metrics.to_dict()
            if metrics_dict:
                message_dict["metrics"] = metrics_dict

        message_dict["created_at"] = self.created_at
        return message_dict

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Message":
        data = dict(data)
        if "metrics" in data:
            if isinstance(data["metrics"], dict):
                data["metrics"] = MessageMetrics.from_dict(data["metrics"])
            elif not isinstance(data["metrics"], MessageMetrics):
                data.pop("metrics")
        return cls(**data)

    def log(self, level: str = "debug") -> None:
        """Log this message to the console for debugging."""
        _logger = {
            "debug": logger.debug,
            "info": logger.info,
            "warning": logger.warning,
            "error": logger.error,
        }.get(level, logger.debug)

        _logger(f"====== {self.role} ======")
        if self.name:
            _logger(f"Name: {self.name}")
        if self.tool_call_id:
            _logger(f"Tool call Id: {self.tool_call_id}")
        if self.content:
            _logger(str(self.content))
        if self.tool_calls:
            _logger(f"Tool Calls: {self.tool_calls}")
        if self.metrics:
            metrics_dict = self.metrics.to_dict()
            if metrics_dict:
                _logger(f"Metrics: {metrics_dict}")
